"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var direccion_1 = require("./direccion");
var mail_1 = require("./mail");
var telefono_1 = require("./telefono");
var persona_1 = require("./persona");
var direccion1 = new direccion_1.default('avenida del sistema', 4, 2, 'B', 28985, 'parla', 'madrid');
var direccion2 = new direccion_1.default('avenida de los astros', 2, 5, 'D', 28986, 'pinto', 'madrid');
var direccion3 = new direccion_1.default('avenida de plutón', 10, 8, 'C', 28934, 'fuenlabrada', 'madrid');
var mail1 = new mail_1.default('personal', 'gema.a.p.7@gmail.com');
var mail2 = new mail_1.default('trabajo', 'jorge.a.p.7@gmail.com');
var mail3 = new mail_1.default('personal', 'rony.a.p.7@gmail.com');
var telefono1 = new telefono_1.default('movil', 638432189);
var telefono2 = new telefono_1.default('movil', 63842319);
var telefono3 = new telefono_1.default('movil', 63812039);
var persona1gema = new persona_1.default('Gema', 'Adame Prudencio', 25, ' 54286716T', 27.12, 'lila', 'F', [direccion1], [mail1], [telefono1], 'Estos son los datos de Gema y le encanta el sushi');
var persona2jorge = new persona_1.default('Jorge', 'Adame Prudencio', 22, ' 54286865P', 23.11, 'verde', 'M', [direccion2], [mail2], [telefono2], 'Estos son los datos de Jorge y le encantan las croquetas de jamón');
var persona3rony = new persona_1.default('Rony', 'Adame Prudencio', 11, ' 5428246H', 8, 'rosa', 'M', [direccion3], [mail3], [telefono3], 'Estos son los datos de Rony y le encanta el arroz con pollo');
console.log(persona1gema);
console.log(persona2jorge);
console.log(persona3rony);
var agenda = new Array(persona1gema, persona2jorge, persona3rony);
var busquedaDNI = "54286716T";
var nuevosDatosPersona = agenda.find(function (persona) { return persona.dni === busquedaDNI; });
var nuevaDireccion = new direccion_1.default("Avenida del Universo", 4, 2, "B", 28981, "Getafe", "Madrid");
var nuevoMail = new mail_1.default("personal", "gemaadameprudencio@gmail.com");
var nuevoTelefono = new telefono_1.default("fmóvil", 638585670);
nuevosDatosPersona.direccionEditada(nuevaDireccion);
nuevosDatosPersona.mailEditado(nuevoMail);
nuevosDatosPersona.telefonoEditado(nuevoTelefono);
console.log(persona1gema);
console.log(persona2jorge);
console.log(persona3rony);
